### ISSUE TITLE
Open to new features?

### ISSUE THREAD

**Issue by colindean** [vertical-blank/sql-formatter#16]
My team is looking for a SQL formatter that meets our needs. `sql-formatter` gets pretty close to what we want but I want to add some features that would satisfy our needs:

1. Option to capitalize reserved words
2. certain functions should not have parameters newlined on commas
3. boolean statements shouldn’t be wrapped across lines with the operator at the beginning of subsequent lines unless the line would exceed some set length
4. JOIN should be at the same indentation level as the parent FROM instead of within it (this one is strange to me, the aforementioned make sense)
5. ON should be inside a JOIN

I'd like to make these be toggleable options. If I made the changes, would you accept a PR?

**Comment by vertical-blank** [comment]
@colindean Yes, I welcome contributions.Thank you.
