### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by david-bouyssie** [vertical-blank/sql-formatter#17]
https://github.com/takayahilton/sql-formatter was recently updated to support Scala Native
This means that vertical-blank's sql-formatter could easily support Scala Native compilation by depending on https://github.com/takayahilton/sql-formatter.

Other tools using vertical-blank's sql-formatter (such as quill) could thus also be ported to SN without having to change the sql-formatter namespace.
And this would add this dependency only for the SN build.

**Comment by vertical-blank** [comment]
Quill uses [this](https://github.com/vertical-blank/scala-sql-formatter) , that  uses java or js library according to runtime.
https://github.com/takayahilton/sql-formatter is written in Pure Scala, then Quill should use it.

This library is for use in JVM languages, so Scala project that runs in Scala.js, Scala Native (such as Quill) should not use this.
Therefore, this should not contain other dependencies.

**Comment by david-bouyssie** [comment]
Yes my mistake. I created this issue in the wrong repo. I thought it was scala-sql-formatter. Sorry for routing error.

Should I reopen this issue in the scala-sql-formatter repo or do you think it's a dead end, and thus I should open a quill issue instead?

**Comment by vertical-blank** [comment]
Yes, thanks! 😄

**Comment by vertical-blank** [comment]
When the PR for Quill is merged, I will freeze scala-sql-formatter repo.
