### ISSUE TITLE
:= format problem

### ISSUE THREAD

**Issue by kaplan441** [vertical-blank/sql-formatter#23]
My script starts as
DECLARE v_number NUMBER := 0;

then SqlFormatter.format(sql). But return like this
DECLARE v_number NUMBER: = 0;
This script throw exception in Oracle. It seperates **:=** operator.

**Comment by vertical-blank** [comment]
Ver 2.0.0, you can extend Formatter to add operator like this.
https://github.com/vertical-blank/sql-formatter/blob/c1e10a0377d741619bf56fcf10effb0b1c535123/src/test/kotlin/com/github/vertical_blank/sqlformatter/ModifiedFormatterTest.kt#L27-L42
