### ISSUE TITLE
v2.0.0 String '||' issue  

### ISSUE THREAD

**Issue by tenie** [vertical-blank/sql-formatter#38]
select '123' || 'abc' from table1

after 

    select
        '123' | | 'abc'
    from
        table1

---
 extra space between the  ||

**Comment by vertical-blank** [comment]
Thank you for reporting,  I'll fix it.

As a workaround, use MySql dialect or write like below.
```
SqlFormatter.extend(cfg -> cfg.plusOperators("||"))
```
