### ISSUE TITLE
@@ operator splitting in Postgres

### ISSUE THREAD

**Issue by kkarasev1** [vertical-blank/sql-formatter#42]
The @@ operator is used in PostgreSQL for text search
https://www.postgresql.org/docs/13/functions-textsearch.html
However, the formatter obtained by SqlFormatter.of(Dialect.PostgreSql) splits those two @ symbols with space, making a query using that operator invalid.

**Comment by kkarasev1** [comment]
This looks to be the same issue as #38  but for different operator - the same workaround works

**Comment by vertical-blank** [comment]
Closed by #48
