### ISSUE TITLE
Oracle quotation operation fails

### ISSUE THREAD

**Issue by hemlac** [vertical-blank/sql-formatter#45]
Using **StandardSql** or **PlSql** dialect, sql-formatter incorrectly interprets the Oracle quotation (**q'...'**)  operator.
For input string `Select q'{test message}' from dual`
gives wrong result
`Select
  q '{test message}'
from
  dual`

**Comment by vertical-blank** [comment]
Fixed by #47

**Comment by hemlac** [comment]
Works fine!
Thank you!
