### ISSUE TITLE
Extra space inserted inside backtick strings

### ISSUE THREAD

**Issue by whiterook6** [vertical-blank/sql-formatter#54]
If I format an SQL string like this:
```
SELECT * FROM `tableName`;
```
The resulting formatted string is like this:
```
SELECT * FROM ` tableName `;
```

The extra spaces break my query. Is there a way to fix this, or an option to disable this particular extra space?

**Comment by vertical-blank** [comment]
@whiterook6 
Treating backquotes as string literals is MySQLs dialect, so try this.
```
SqlFormatter
  .of(Dialect.MySql)
  .format("SELECT * FROM `tableName`;")
```

**Comment by whiterook6** [comment]
That seems to work! Thank you.
