### ISSUE TITLE
Add @@SESSION as reserved word for MySQL

### ISSUE THREAD

**Issue by zendesk-jjtheo** [vertical-blank/sql-formatter#59]
`@@SESSION` is a reserved word in MySQL. https://dev.mysql.com/doc/refman/8.0/en/session-state-tracking.html
The formatter is currently adding a space after the first `@` as it's considering it as a special word char.

Maybe a same fix as #42 would work? although it's not an operator in MySQL

**Comment by vertical-blank** [comment]
@zendesk-jjtheo 
As a workaround, try this.
```java
String sql = SqlFormatter.extend(cfg -> cfg.plusReservedWords("@@SESSION"))
            .format("SET @@SESSION.session_track_transaction_info='CHARACTERISTICS';");
System.out.println(sql);
```

output:
```
SET
  @@SESSION.session_track_transaction_info = 'CHARACTERISTICS';
```

**Comment by zendesk-jjtheo** [comment]
@vertical-blank Thank you!
